### ISSUE TITLE
Update eslint rules for errors

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2068]
in PR https://github.com/zowe/vscode-extension-for-zowe/pull/2029 we spoke of adding rules that will throw errors and require developer to fix.  Some mentioned include:

1. "no-console"
2. "no-duplicate-imports"

List of all rules that can be considered https://typescript-eslint.io/rules/

I suggest also including:

1. "no-shadow"
2. "no-unused-vars"

We will have a new [eslintrc file at the top level](https://github.com/zowe/vscode-extension-for-zowe/blob/main/.eslintrc.yaml) when the PR mentioned above is merged and can set our rules here and remove the individual package eslintrc files for [zowe-explorer-ftp-extension](https://github.com/zowe/vscode-extension-for-zowe/blob/main/packages/zowe-explorer-ftp-extension/.eslintrc.yaml) and [zowe-explorer-api](https://github.com/zowe/vscode-extension-for-zowe/blob/main/packages/zowe-explorer-api/.eslintrc.yaml) transferring some of the rules listed for errors into the top level file.

*Edit by traeok:* 

Here is the current ruleset given the transition from TSLint to ESLint, for reference:

```yaml
  "@typescript-eslint/consistent-type-assertions": warn
  "@typescript-eslint/no-namespace": warn
  "@typescript-eslint/no-var-requires": warn
  "@typescript-eslint/no-unused-expressions": warn
  curly: warn
  max-len:
    - warn
    - code: 150
  no-console: warn
  no-duplicate-case: warn
  no-duplicate-imports: warn
  no-extra-bind: warn
  no-irregular-whitespace: warn
  no-magic-numbers:
    - warn
    - "ignore": [-1, 0, 1, 2, 4]
  no-multiple-empty-lines: warn
  no-return-await: warn
  no-sequences: warn
  no-sparse-arrays: warn
  prefer-object-spread: warn
  space-in-parens: warn
```

Finally, we might want to consider adding the SonarJS plugin for ESLint. This should help with catching code smells before they are reported from SonarCloud. https://github.com/SonarSource/eslint-plugin-sonarjs (Thanks @zFernand0 for mentioning this!)
